name: hrrr
channels:
  - conda-forge
dependencies:
  - python=3.8
  - dask
  - cfgrib
  - fsspec
  - kerchunk
  - netcdf4
  - pandas
  - s3fs
  - xarray
  - zarr
  # JupyterLab extensions
  - jupyterlab>=3
  - dask-labextension
  - ipywidgets