name: hrrr
channels:
  - conda-forge
dependencies:
  - python=3.9
  - cfgrib
  - dask
  - fsspec
  - kerchunk
  - netcdf4
  - pandas
  - python-graphviz
  - s3fs
  - xarray
  - zarr
  # JupyterLab extensions
  - jupyterlab>=3
  - dask-labextension
  - ipywidgets
  # holoviz
  - datashader
  - geoviews
  - hvplot
